### PR TITLE
Fix app build

### PR DESCRIPTION
**Pull request by hedgerwang**
xcode can't build the current app thus there is no direct way to test the app.

I followed the instruction and ran the command `react-native init NavigationExampleApp` which generated a bunch of files automatically.

I tested the new build and it works for me.

### CODE REVIEW

**Comment by hedgerwang** [comment]
this is the screenshot of the app

image

**Comment by lucasfeliciano** [comment]
You don't need run `react-native init` to run the project.

This are the steps:
- Clone the project
- npm install
- open the xcode file 
- run it

**Comment by hedgerwang** [comment]
That's the right step to test the app except that the current build does not work.

The current project can't be build with xcode. I ran `react-native init` to generate the updated files and move the into this project.

**Comment by ericvicenti** [comment]
Ah, thanks! I was also confused about these changes

**Comment by lucasfeliciano** [comment]
So I dont understand why it was working for me even before the merge.

**Pull request merged**
