### PR TITLE
Rework the NavigationHeader

### PR DESCRIPTION
**Pull request by satya164**
Make `<NavigationHeader />` work on both iOS and Android, and make it more customizable. Refer #20 

iOS:

ios

Android:

android

### CODE REVIEW

**Comment by ericvicenti** [comment]
Sorry about the delay on this Satyajit! I'll merge it tonight

**Comment by satya164** [comment]
Cool. Thanks :)

**Comment by ericvicenti** [comment]
I landed #19 tonight, so it caused some thrash in the code

I've done most of the merging on this branch here: https://github.com/ericvicenti/navigation-rfc/tree/navheader

But there is still a bridge number error that shows up, as well as some small formatting issues. Would you mind taking a look?

**Comment by satya164** [comment]
@ericvicenti Hey. Will do ASAP. Thanks :)

**Comment by satya164** [comment]
Will be great if you can comment on the formatting issues :)

**Comment by satya164** [comment]
Merged master to my branch.

**Comment by satya164** [comment]
BTW I see this error on master (after running AsyncStorage.clear(), otherwise it wasn't displaying anything).

This only happens on iOS, not Android.

iphone 5 - iphone 5 - ios 9 2 13c75 simulator today at 5 33 39 pm

**Comment by ericvicenti** [comment]
I only noticed that issue after I patched in your header changes

**Comment by satya164** [comment]
@ericvicenti Hey. Seems that it only happens if Chrome debugger is connected. (Both in master and my branch). This not specifically related to my branch.

Here is a screencast confirming that it happens on master - https://www.youtube.com/watch?v=KdSdBDgXFIE

Sorry, I would've taken a hit at this, but I've no idea where it's coming from and why :(

**Comment by ericvicenti** [comment]
Ah, in that case I'll merge your PR now! The redbox seems to be caused by the transform translateX in the NavigationCard.. hrmmm. It could be a bug in Animated, but more likely something going wrong with chrome debugging.

**Comment by satya164** [comment]
Awesome! :tada:

**Comment by satya164** [comment]
I'm also seeing the error on the master branch of RN with old Navigator code.

**Pull request merged**
